global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'profiler-metrics'
    static_configs:
      - targets: ['proxy:8082']
    metrics_path: "/metrics"
    scheme: https
    tls_config:
      insecure_skip_verify: true
